### ISSUE TITLE
Insert data used HTTP POST

### ISSUE THREAD

**Issue by CoderJava** [PatilShreyas/Flutter2GoogleSheets-Demo#2]
Hi Team,
I see in your Flutter code you used HTTP GET for send data to Google Sheet. Can you tell me why you use it and why you not used HTTP POST for send data?

https://github.com/PatilShreyas/Flutter2GoogleSheets-Demo/blob/15a2dad7842d2b5ededfc200b70b51d787ec303c/lib/controller/form_controller.dart#L24

Thanks.

**Comment by PatilShreyas** [comment]
Actually, as a good approach, at start I also tried to use POST request. But what was happening that everytime I send HTTP POST requests, I was getting `Error 302: Temporarily Moved`. I again tested it with POSTMan but it's fine but flutter was giving that error. After that I tried GET request and it's working fine. That's the reason why I used GET request. I'm finding solution on it. Once I got it, I'll update it. Thanks!

**Comment by CoderJava** [comment]
> Actually, as a good approach, at start I also tried to use POST request. But what was happening that everytime I send HTTP POST requests, I was getting `Error 302: Temporarily Moved`. I again tested it with POSTMan but it's fine but flutter was giving that error. After that I tried GET request and it's working fine. That's the reason why I used GET request. I'm finding solution on it. Once I got it, I'll update it. Thanks!

Ok. I'm created #3 pull request for it. Please check and test it. Thanks.

**Comment by PatilShreyas** [comment]
Thanks for your interest and help for making it more perfect!

**Comment by CoderJava** [comment]
Merged PR https://github.com/PatilShreyas/Flutter2GoogleSheets-Demo/pull/3
